debug

diff --git a/.github/workflows/plan.yml b/.github/workflows/plan.yml
--- a/.github/workflows/plan.yml
+++ b/.github/workflows/plan.yml
@@ -1,6 +1,9 @@
-name: terraform plan
+name: terraform plan amd apply
 on:
-  pull_request
+  pull_request:
+  push:
+    branches:
+      - main
 env:
   AWS_REGION : "ap-northeast-1"
 permissions:
@@ -28,11 +31,13 @@ jobs:
         run: |
           WORKDIRS=$(echo '${{ toJSON(steps.changes.outputs) }}' | jq '. | to_entries[] | select(.value == "true") | .key') 
           echo "workdirs=$(echo $WORKDIRS | jq -sc '.')" >> $GITHUB_OUTPUT
+
   plan:
     runs-on: ubuntu-latest
     needs: determine-workdir
     if: needs.determine-workdir.outputs.workdirs != '[]'
     strategy:
+      fail-fast: false
       matrix:
         workdir: ${{ fromJSON(needs.determine-workdir.outputs.workdirs) }}
     steps:
@@ -44,8 +49,8 @@ jobs:
       - name: Configure aws credentials
         uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502 # v4.0.2
         with:
-          role-to-assume: arn:aws:iam::${{ secrets[env.AWS_ACCOUNT_ID] }}:role/github_actions
-          role-session-name: MyGithubActionsSession
+          role-to-assume: arn:aws:iam::${{ secrets[env.AWS_ACCOUNT_ID] }}:role/github_actions_plan
+          role-session-name: PlanSession
           aws-region: ${{ env.AWS_REGION }}
       - name: Setup terraform
         uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3.1.2
@@ -56,4 +61,43 @@ jobs:
         working-directory: ${{ matrix.workdir }}
       - name: Terraform plan
         run: terraform plan
+        working-directory: ${{ matrix.workdir }}
+        continue-on-error: true
+      - name: Save Plan Status
+        id: save-status
+        run: |
+          if [ $? -eq 0 ]; then
+            echo "matrix-status=success" >> $GITHUB_OUTPUT
+          else
+            echo "matrix-status=failed" >> $GITHUB_OUTPUT
+        
+  apply:
+    runs-on: ubuntu-latest
+    if: ${{ needs.plan.outputs.matrix-results == 'success' && github.event_name == 'push' && github.ref == 'refs/heads/main' }}
+    needs: determine-workdir
+    strategy:
+      fail-fast: false
+      matrix:
+        workdir: ${{ fromJSON(needs.determine-workdir.outputs.workdirs) }}
+    steps:
+      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
+
+      - name: Configure AWS credentials for Apply
+        uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502
+        with:
+          role-to-assume: arn:aws:iam::${{ secrets[env.AWS_ACCOUNT_ID] }}:role/github_actions_apply
+          role-session-name: ApplySession
+          aws-region: ${{ env.AWS_REGION }}
+
+      - name: Setup Terraform
+        uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd
+        with:
+          terraform_version: "1.9.8"
+
+      - name: Terraform Init
+        run: terraform init
+        working-directory: ${{ matrix.workdir }}
+
+      - name: Terraform Apply
+        run: terraform apply -auto-approve
         working-directory: ${{ matrix.workdir }}
